// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhypyamklphdsyzpwvfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeXB5YW1rbHBoZHN5enB3dmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzk3OTQsImV4cCI6MjA1Nzg1NTc5NH0.N3h8f6nR0rh02fn8ItBfPq3fHKszGU40Yqq1KhTrCZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);